chicken-egg-xlib: Add patch to fix host contamination
Fixes:
    ERROR: QA Issue: chicken-egg-xlib: The install log indicates
    that host include and/or library paths were used.

Change-Id: I8ccfa63a5b9e1e950ad1f1b1107934862dd00538
Signed-off-by: Fabio Berton <fabio.berton@ossystems.com.br>