chicken-egg-xlib-utils: add patch to fix host contamination
Fixes:

  ERROR: QA Issue: chicken-egg-xlib-utils: The install log indicates
  that host include and/or library paths were used.

Change-Id: Ib6ada46eb8cdeca502b5b2594edb4cc1b43ce9ee
Signed-off-by: Mario Domenech Goulart <mario@ossystems.com.br>